import type { Direction } from "@/types/game";

export const mockGameBoardWithWalls: { Name: string; Walls: Direction[] }[][] = [
    [
        { Name: "EmptySpace", Walls: [] },
        { Name: "EmptySpace", Walls: ["South"] },
        { Name: "EmptySpace", Walls: ["South", "East"] },
        { Name: "EmptySpace", Walls: ["West"] },
        { Name: "EmptySpace", Walls: ["East"] },
        { Name: "EmptySpace", Walls: ["West", "South"] },
        { Name: "EmptySpace", Walls: ["South"] },
        { Name: "EmptySpace", Walls: [] },
        { Name: "EmptySpace", Walls: [] },
        { Name: "EmptySpace", Walls: [] },
    ],
    [
        { Name: "EmptySpace", Walls: [] },
        { Name: "EmptySpace", Walls: ["North"] },
        { Name: "EmptySpace", Walls: ["North"] },
        { Name: "EmptySpace", Walls: ["East"] },
        { Name: "EmptySpace", Walls: ["West"] },
        { Name: "EmptySpace", Walls: ["North"] },
        { Name: "EmptySpace", Walls: ["North", "South"] },
        { Name: "EmptySpace", Walls: [] },
        { Name: "EmptySpace", Walls: [] },
        { Name: "EmptySpace", Walls: ["South"] },
    ],
    [
        { Name: "EmptySpace", Walls: ["South"] },
        { Name: "EmptySpace", Walls: ["South", "East"] },
        { Name: "EmptySpace", Walls: ["West"] },
        { Name: "EmptySpace", Walls: ["South"] },
        { Name: "EmptySpace", Walls: ["South"] },
        { Name: "EmptySpace", Walls: ["South"] },
        { Name: "EmptySpace", Walls: ["North"] },
        { Name: "EmptySpace", Walls: ["South", "East"] },
        { Name: "EmptySpace", Walls: ["West", "South"] },
        { Name: "EmptySpace", Walls: ["North"] },
    ],
    [
        { Name: "EmptySpace", Walls: ["North", "South", "East"] },
        { Name: "EmptySpace", Walls: ["West", "North"] },
        { Name: "EmptySpace", Walls: ["East", "South"] },
        { Name: "EmptySpace", Walls: ["West", "North"] },
        { Name: "EmptySpace", Walls: ["North"] },
        { Name: "EmptySpace", Walls: ["North"] },
        { Name: "EmptySpace", Walls: ["South"] },
        { Name: "EmptySpace", Walls: ["North"] },
        { Name: "EmptySpace", Walls: ["North"] },
        { Name: "EmptySpace", Walls: ["South"] },
    ],
    [
        { Name: "EmptySpace", Walls: ["North"] },
        { Name: "EmptySpace", Walls: [] },
        { Name: "EmptySpace", Walls: ["North"] },
        { Name: "EmptySpace", Walls: ["South", "East"] },
        { Name: "EmptySpace", Walls: ["West", "East"] },
        { Name: "EmptySpace", Walls: ["West"] },
        { Name: "EmptySpace", Walls: ["North"] },
        { Name: "EmptySpace", Walls: ["South"] },
        { Name: "EmptySpace", Walls: ["East"] },
        { Name: "EmptySpace", Walls: ["West", "North"] },
    ],
    [
        { Name: "EmptySpace", Walls: ["East"] },
        { Name: "EmptySpace", Walls: ["West", "East"] },
        { Name: "EmptySpace", Walls: ["West", "East"] },
        { Name: "EmptySpace", Walls: ["West", "North"] },
        { Name: "EmptySpace", Walls: [] },
        { Name: "EmptySpace", Walls: ["South", "East"] },
        { Name: "EmptySpace", Walls: ["West"] },
        { Name: "EmptySpace", Walls: ["North"] },
        { Name: "EmptySpace", Walls: ["East"] },
        { Name: "EmptySpace", Walls: ["West"] },
    ],
    [
        { Name: "EmptySpace", Walls: [] },
        { Name: "EmptySpace", Walls: [] },
        { Name: "EmptySpace", Walls: ["South", "East"] },
        { Name: "EmptySpace", Walls: ["West", "East"] },
        { Name: "EmptySpace", Walls: ["West"] },
        { Name: "EmptySpace", Walls: ["North"] },
        { Name: "EmptySpace", Walls: [] },
        { Name: "EmptySpace", Walls: ["South"] },
        { Name: "EmptySpace", Walls: ["East"] },
        { Name: "EmptySpace", Walls: ["West"] },
    ],
    [
        { Name: "EmptySpace", Walls: [] },
        { Name: "EmptySpace", Walls: ["East", "South"] },
        { Name: "EmptySpace", Walls: ["West", "North", "East"] },
        { Name: "EmptySpace", Walls: ["West"] },
        { Name: "EmptySpace", Walls: [] },
        { Name: "EmptySpace", Walls: [] },
        { Name: "EmptySpace", Walls: ["South"] },
        { Name: "EmptySpace", Walls: ["North", "South"] },
        { Name: "EmptySpace", Walls: ["South"] },
        { Name: "EmptySpace", Walls: ["South"] },
    ],
    [
        { Name: "EmptySpace", Walls: ["East", "South"] },
        { Name: "EmptySpace", Walls: ["West", "North"] },
        { Name: "EmptySpace", Walls: [] },
        { Name: "EmptySpace", Walls: ["East"] },
        { Name: "EmptySpace", Walls: ["West", "South"] },
        { Name: "EmptySpace", Walls: ["East"] },
        { Name: "EmptySpace", Walls: ["West", "North"] },
        { Name: "EmptySpace", Walls: ["North", "East", "South"] },
        { Name: "EmptySpace", Walls: ["West", "North"] },
        { Name: "EmptySpace", Walls: ["North"] },
    ],
    [
        { Name: "EmptySpace", Walls: ["North", "East"] },
        { Name: "EmptySpace", Walls: ["West"] },
        { Name: "EmptySpace", Walls: ["East"] },
        { Name: "EmptySpace", Walls: ["West", "East"] },
        { Name: "EmptySpace", Walls: ["West", "North"] },
        { Name: "EmptySpace", Walls: ["East"] },
        { Name: "EmptySpace", Walls: ["West", "East"] },
        { Name: "EmptySpace", Walls: ["West", "North"] },
        { Name: "EmptySpace", Walls: ["East"] },
        { Name: "EmptySpace", Walls: ["West"] },
    ],
];
